// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwkvY9nmXILulp-rMEtuEyMUWEO-z6G4',
    appId: '1:913337528884:web:109e1910fa82aa2ede1061',
    messagingSenderId: '913337528884',
    projectId: 'oru-phones-1b57d',
    authDomain: 'oru-phones-1b57d.firebaseapp.com',
    storageBucket: 'oru-phones-1b57d.firebasestorage.app',
    measurementId: 'G-1RZ8RBM88S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Z_HCPM4kBQIRTELCdrARPyYgAT7zITI',
    appId: '1:913337528884:android:b3654273165bcbacde1061',
    messagingSenderId: '913337528884',
    projectId: 'oru-phones-1b57d',
    storageBucket: 'oru-phones-1b57d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ajcD8pWtVgbUeKau3RxKUZcHrhbTGjY',
    appId: '1:913337528884:ios:76e6ea97ee5fd4e0de1061',
    messagingSenderId: '913337528884',
    projectId: 'oru-phones-1b57d',
    storageBucket: 'oru-phones-1b57d.firebasestorage.app',
    iosBundleId: 'com.example.oruPhones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ajcD8pWtVgbUeKau3RxKUZcHrhbTGjY',
    appId: '1:913337528884:ios:76e6ea97ee5fd4e0de1061',
    messagingSenderId: '913337528884',
    projectId: 'oru-phones-1b57d',
    storageBucket: 'oru-phones-1b57d.firebasestorage.app',
    iosBundleId: 'com.example.oruPhones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXwkvY9nmXILulp-rMEtuEyMUWEO-z6G4',
    appId: '1:913337528884:web:8335cb4b4a3deeddde1061',
    messagingSenderId: '913337528884',
    projectId: 'oru-phones-1b57d',
    authDomain: 'oru-phones-1b57d.firebaseapp.com',
    storageBucket: 'oru-phones-1b57d.firebasestorage.app',
    measurementId: 'G-XCNE4T84LZ',
  );
}
